### ISSUE TITLE
Incorrect formatting of Parenthesis blocks

### ISSUE THREAD

**Issue by B-Ricey763** [Enter-tainer/typstyle#107]
I am using `tinymist` with `formatterType = 'typstyle` on Neovim, and I'm getting different formatting results than the we app. Take this math block for example:
```
$
  k^2 + k + 2 k + 2 &quad "Add" 2k + 2 "to both sides" \
  = 2 n + 2 k + 2 \
  = 2(
    n + k + 1
  ) &quad "This is even by def of even" \
  = (
    k^2 + 2 k + 1
  ) + k + 1 = 2 (
    a + k + 1
  ) &quad "Math"
$
```
In my editor, this is the formatted output of this code, with each parenthesis opening a new line as if it were a body of a function or something. When I take this same exact string and put it in the web app, I get:
```
 $
  k^2 + k + 2 k + 2 &quad "Add" 2k + 2 "to both sides" \
  = 2 n + 2 k + 2 \
  = 2(n + k + 1) &quad "This is even by def of even" \
  = (k^2 + 2 k + 1) + k + 1 = 2 (a + k + 1) &quad "Math"
$
```
I verified that my buffer is using `tinymist` as the formatter, but I don't know how to verify that it is using typstyle specifically. This is not an issue with my print width since stuff like `O(n)` still takes up 3 lines. Any help would be appreciated, because I assume this is on my end and not an actual bug.

**Comment by Enter-tainer** [comment]
<img width="702" alt="image" src="https://github.com/user-attachments/assets/6e421fb9-fdad-4572-968d-745d5c7697b9">

I can reproduce this if I set column width to a very low number

**Comment by Enter-tainer** [comment]
BTW, I think the formatting result is not "incorrect"? They are just kind of... undesired, I guess

**Comment by B-Ricey763** [comment]
Okay that's really odd, `tinymist`s server configuration says the default `formatterPrintWidth` is 120 characters, but when manually setting it in my config to 80 it fixes everything, so it must be an issue with that setting on their end. Thanks for your help @Enter-tainer!
