### ISSUE TITLE
Add more descriptive use of --column argument.

### ISSUE THREAD

**Issue by Blackgaurd** [Enter-tainer/typstyle#121]
The README is not very descriptive for how the --column cli argument is used, nor can I figure out a way for it to work.

**Comment by Enter-tainer** [comment]
can you elaborate more about when it doesnt work? see also https://enter-tainer.github.io/typstyle/limitations/

**Comment by Enter-tainer** [comment]
I hope this link is useful to you: https://github.com/Enter-tainer/typstyle/issues/75#issuecomment-2132040172

Indeed the doc can be improved and contribution is welcome

**Comment by Blackgaurd** [comment]
Yes, that answers my question, thanks for your response!
