### ISSUE TITLE
Define number of indent spaces.

### ISSUE THREAD

**Issue by PhosCity** [Enter-tainer/typstyle#122]
Is there a way for me to define the number of indent spaces in typstyle? I wanted the number of indent space to be 4 but typstyle defaults at 2 spaces.

**Comment by Enter-tainer** [comment]
i believe this is a deplicate of #116

**Comment by PhosCity** [comment]
It is! In my defense, I did search for issues about indents and didn't find any but did not search for issues about tabs. I'll close this issue and follow that one.
