### ISSUE TITLE
Windows binary does not start 

### ISSUE THREAD

**Issue by ramkumarkb** [Enter-tainer/typstyle#134]
# Steps
Installed the Windows binary from the latest [Github release](https://github.com/Enter-tainer/typstyle/releases/download/v0.11.33/typstyle-x86_64-pc-windows-msvc.exe) page

# Error Screen Shot

![image (7)](https://github.com/user-attachments/assets/44f16e6a-1002-4734-a1c8-8a0c5d699553)

Rather strangely, the windows title says `Unsupported 16-bit application`.

**Comment by Enter-tainer** [comment]
that's interesting

**Comment by Enter-tainer** [comment]
it works on my machine
![image](https://github.com/user-attachments/assets/28c71ba8-cecb-4343-aa68-cd6cd922c99a)

**Comment by Enter-tainer** [comment]
I'm on windows 11 23h2(22631)

**Comment by Enter-tainer** [comment]
pls reopen if you someone can also reproduce it

**Comment by ramkumarkb** [comment]
@Enter-tainer - Sincere apologies for coming back earlier. Please close this issue as this seems to be very specific to my Windows environment. Thank you !
