### ISSUE TITLE
Indented comment blocks drifting right

### ISSUE THREAD

**Issue by leana8959** [Enter-tainer/typstyle#136]
Hello,

I noticed that comment blocks (with `/* */`), the closing tag drifts to the right when it's in a indented block.

Before:
```typ
- foo
  /* bar
  */
```

After:
```typ
- foo
  /* bar
    */
```

After multiple runs the `*/` keeps drifting to the right, the result never stablises.

Thanks for the project !

**Comment by Enter-tainer** [comment]
looks like a bug. i will check when i am back from vacation
