### ISSUE TITLE
Strange formatting of long show-set rule

### ISSUE THREAD

**Issue by Andrew15-5** [Enter-tainer/typstyle#143]
```typ
#show heading.where(level: 2): set heading(numbering: (..n) => [#n.pos().at(1).])
```

with `typstyle -c 80`:

```typ
#show heading.where(level: 2): set heading(numbering: (
  ..n,
) => [#n.pos().at(1).])
```

I think it's much more readable to prefer first breaking by 1 parameter per line:

```typ
#show heading.where(level: 2): set heading(
  numbering: (..n) => [#n.pos().at(1).],
)
```

**Comment by Enter-tainer** [comment]
I'm not entirely sure what's happending but it looks like this falls into a special handling for single parameter function call. I will look into it later.

**Comment by QuadnucYard** [comment]
In the current implementation, as long as the call/set has exactly one arg which is not func-call, we will force that arg to stick with the paren. Without this rule, the code will be formatted as you suggested.
Maybe we can decide this behavior based on context, e.g., in show-rule, the arg is complex enough, etc.
Anyway, it's tough to strike a balance between simple cases (the arg is just one literal or ident) and complex cases (as put here).

**Comment by Andrew15-5** [comment]
Now it's 7 lines instead of 3. Isn't this too much? It's really unnecessary stretched, considering that there is a lot of room on the right. Which line limit is used for tests?

**Comment by Enter-tainer** [comment]
> Now it's 7 lines instead of 3. Isn't this too much? It's really unnecessary stretched, considering that there is a lot of room on the right. Which line limit is used for tests?
> 
> https://github.com/QuadnucYard/typstyle/blob/58791a2f22a376dc4363bd9d55bf38bd455ce324/tests/snapshots/assets__check_file%40unit-show-show-set.typ-0.snap

you are seeing the 0 width snapshot. typstyle will break at every possible position. this is only for debugging. for real world use case, please see -80 and -120 snapshots.

**Comment by Andrew15-5** [comment]
Oh, I didn't notice that there are _multiple_ tests for the same thing. All good.
