### ISSUE TITLE
Spaces on the inside of braces are removed after formatting

### ISSUE THREAD

**Issue by QuadnucYard** [Enter-tainer/typstyle#144]
```typst
${ a b } ( 1 2 ) [ | | ]$
```
will be formatted to
```typst
${a b} (1 2) [| |]$
```
and then
```typst
${a b} (1 2) [||]$
```
seemingly unintentional.

This is a destructive bug as it will produce `⟦⟧` instead of `[| |]`

**Comment by Enter-tainer** [comment]
This is a tricky case. These spaces don't contribute to rendering result. But the `[ | | ]` case is very special. I don't know how to handle it yet. We might need to keep spaces if there is some.
