### ISSUE TITLE
formatter is adding sometimes a trailing coma 

### ISSUE THREAD

**Issue by danieltomasz** [Enter-tainer/typstyle#147]
Installing latest tinymist in new profile and setting Tinymist: Formatter Mode to `typstyle`, then rightclick "Format document"

results in adding trailing comma to this code 
```
// Remove gridlines from tables
#set table(
  inset: 6pt,
  stroke: none
)
```
So the results is 

```
// Remove gridlines from tables
#set table(
  inset: 6pt,
  stroke: none,
)
```
`typstfmt` format it correctly into 
```
// Remove gridlines from tables
#set table(inset: 6pt, stroke: none)
```

**Comment by Enter-tainer** [comment]
could you elaberate? i dont think it's a bug

**Comment by danieltomasz** [comment]
@Enter-tainer is there any official style guide for typst? Or this is just meant to be useful for code change management in version control? (decision by formatter design like black/ruff in Python)

**Comment by Enter-tainer** [comment]
AFAIK there isn't a style guide. 

> Subjective decision by formatter design like black/ruff in Python

Correct. Actually I add extra code for adding trailing comma

**Comment by danieltomasz** [comment]
Do you have something to exclude line from formatting like # fmt: off
black?

**Comment by Enter-tainer** [comment]
yes, add `//@typstyle off` before that ast node should disable formatting.

you may get more information about this in readme.md

**Comment by danieltomasz** [comment]
thanks for the feedback!
