### ISSUE TITLE
[Feature Request] Support for soft wrapping lines

### ISSUE THREAD

**Issue by FlyinPancake** [Enter-tainer/typstyle#148]
I'm coming from typstfmt and I really like soft line-wraps. Is there any chance implementing this?

If the feature is already in the project I was not able to find how to enable it. 

thanks :)

**Comment by Enter-tainer** [comment]
soft line wraps has been discussed before and it's very hard to implement it correctly. for cjk languages, soft wrapping is impossible in current typst

**Comment by Enter-tainer** [comment]
https://github.com/Enter-tainer/typstyle/issues/75 previous discussion

**Comment by FlyinPancake** [comment]
I'll just create an action to run the code through typstfmt every so often to keep the line length managable :D

keep up the awesome work and sorry for not reading the issues carefully enough

**Comment by istathar** [comment]
I've read through some of the challenges that have been encountered in the past, but if it's a block of plain text (not a `#function` call) can we just wrap that?
