### ISSUE TITLE
Preserve all comments as possible

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typstyle#16]
- [x] Comments in codeblocks and content blocks
- [x] Comments in array
- [x] Comments in dict
- [x] Comments in function arg

**Comment by Enter-tainer** [comment]
we currently refuse to format all nodes that contains comment. So it won't eat comments now. But I think this can be further improved in future

**Comment by QuadnucYard** [comment]
I think this has been resolved by #153, #154, #167.
