### ISSUE TITLE
typstyle is available on Arch Linux CN repo

### ISSUE THREAD

**Issue by Jisu-Woniu** [Enter-tainer/typstyle#210]
See <https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/typstyle>

Repo help: <https://www.archlinuxcn.org/archlinux-cn-repo-and-mirror/> & <https://github.com/archlinuxcn/repo>

Repology does not currently include Arch Linux CN repo information, so maybe add a link to it in the README?

**Comment by Enter-tainer** [comment]
congratulations! i'm on vacation recently and i can add it when i'm back. pr is also welcome!
