### ISSUE TITLE
CLI can't format multiple files

### ISSUE THREAD

**Issue by Nilstrieb** [Enter-tainer/typstyle#49]
typstyle is pretty cool, so I want to use it to format all my files.
I tried doing `typstyle -i ./**/*.typ` to format them all, but that doesn't work, as it only accepts a single argument.
Without `-i` it doesn't really make sense to accept multiple arguments, but with `-i` it does.

**Comment by Enter-tainer** [comment]
I will look into it. it won't be very hard.

**Comment by Enter-tainer** [comment]
BTW, you may also want to try [tinymist](https://github.com/Myriad-Dreamin/tinymist), which embeds typstyle in lsp

**Comment by Enter-tainer** [comment]
v0.11.13 just published.

**Comment by Nilstrieb** [comment]
cool, thanks!
