### ISSUE TITLE
Benefit from incremental reparsing

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Enter-tainer/typstyle#51]
We can provide a formatting function receiving `typst::syntax::Source` to gain benefit from incremental reparsing. Now all mainstream typst servers can do incremental source code reparsing to reduce overhead to parse, also preserve stable `typst::syntax::Span` in AST nodes across user editions (to help cache). However, typstyle can only receive a raw string and parse from scratch inside of itself formatting procedure, which is a bit wasty.

**Comment by Enter-tainer** [comment]
good catch. will do it
