### ISSUE TITLE
Empty lines in content block is indented

### ISSUE THREAD

**Issue by leana8959** [Enter-tainer/typstyle#62]
Hello,

I noticed that empty lines in a content block are indented. Here's an example:

Before:
```typ
#test_box[
  this is a line

  this is a line after a space
]
```
After:
```typ
#test_box[
  this is a line
␣␣
  this is a line after a space
]
```
(with `␣␣` marking the two spaces added)

Since the project aims to not touch content blocks, I wonder if this is intentional ?

Thank you for your time !

**Comment by Enter-tainer** [comment]
![Screenshot_2024-05-01-16-09-32-198_com.microsoft.emmx.jpg](https://github.com/Enter-tainer/typstyle/assets/25521218/89ea49b9-6332-4bb2-a600-cbaf7feb5998)

which typstyle version are you using? typstyle trims all trailing spaces from about 1 month ago

**Comment by Enter-tainer** [comment]
I'm closing this since I believe it comes from outdated typstyle. Feel free to reopen this issue if it's not.

**Comment by leana8959** [comment]
Hello, thanks for the reply.

Indeed, I was using 0.11.13. However, after compiling from source (tag v0.11.16), I'm still getting the same behaviour.

Here's the version information if it helps:
```text
typstyle
Version:             0.11.16
Build Timestamp:     2024-05-01T21:00:43.456037000Z
Build Git Describe:  v0.11.16
Commit SHA:          19872855530d55a296778af3f43626e8a926ff69
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: aarch64-apple-darwin
```

**Comment by Enter-tainer** [comment]
cli doesnt strip space. wasm and library does it. i will fix it soon
