### ISSUE TITLE
Format all files inside a directory.

### ISSUE THREAD

**Issue by mainrs** [Enter-tainer/typstyle#67]
I expected `typstyle .` to just format all files inplace for me that it can find recursively.

Would you be open to either have the above command or a simple `typstyle` do this as a special case? This makes it easier to integrate the CLI into other tooling. Right now, every time I want to automate some stuff with `typstyle`, I have to traverse my files on my own.

**Comment by Enter-tainer** [comment]
currently i follow the interface of clang-format. and not doing inplace format aggressively. what you've proposed is worth considering

**Comment by Enter-tainer** [comment]
i remember `ruff format` is closed to what you've described

**Comment by Enter-tainer** [comment]
https://stackoverflow.com/questions/28896909/how-to-call-clang-format-over-a-cpp-project-folder clang-format doesn't provide such command 🤣 . Maybe i can add a subcommand to do that, like `typstyle format` or something

**Comment by mainrs** [comment]
Could even be a really explicit name like `format-all` or something like that.
