### ISSUE TITLE
Use anotated tag when generating a release

### ISSUE THREAD

**Issue by Jisu-Woniu** [Enter-tainer/typstyle#70]
Hello there. I maintain a `typstyle-git` package on AUR, and I notice that there is a minor problem with the releases.

The recent releases(since v0.11.16) are tagged with lightweight tags. As in manpage [git-tag(1)](https://man.archlinux.org/man/git-tag.1#DESCRIPTION):

> Tag objects (created with -a, -s, or -u) are called "annotated" tags; they contain a creation date, the tagger name and e-mail, a tagging message, and an optional GnuPG signature. Whereas a "lightweight" tag is simply a name for an object (usually a commit object).
>
> Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight tags by default.

By the time of writing, when I use `git describe --long | sed 's/\([^-]*-\)g/r\1/;s/-/./g'` to generate package version, instead of

```
v0.11.21.r0.05f9e34
```

I got

```
v0.11.15.r14.05f9e34
```

**Comment by Enter-tainer** [comment]
> I maintain a typstyle-git package on AUR, and I notice that there is a minor problem with the releases.

thank you for your excellent work! 

> Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels.

i didnt know this before. thank you for letting me know this. i will switch to git tag -s in next release

**Comment by Enter-tainer** [comment]
Hi, i use signed tag `git tag -s ` in latest release. but it looks like in AUR the version still looks odd. https://aur.archlinux.org/packages/typstyle-git Do I need take further actions? cc @Jisu-Woniu

**Comment by Jisu-Woniu** [comment]
No, because the -git package generates its `pkgver` at build-time through the `pkgver()` function, so it doesn't need to be updated unless the build process changes.

**Comment by Jisu-Woniu** [comment]
I have already tested it locally, the version is correct on my machine.

**Comment by Enter-tainer** [comment]
Thank you!
