### ISSUE TITLE
Prioritize saving vertical space in the code more

### ISSUE THREAD

**Issue by BattleCh1cken** [Enter-tainer/typstyle#73]
- typstyle version: 0.11.17

### Observed Problem

When writing Typst code, I often find myself writing things enclosed inside `()`. Often I want each item enclosed on its own line, but often there isn't very much code inside, but the formatter expands it anyway.

For example I might write this code:

```typst
([content],)
```
which the formatter expands to:

```typst
(
  [content],
)
```

Or perhaps a function call from a dictionary:
```typst
(theme.cover)(ctx: ctx)
```
which the formatter expands to this:

```
(
  theme.cover
)(ctx: ctx)
```

Or even simple function calls which often get expanded in a way that prioritizes saving horizontal space over vertical space.

This:
```typst
assert.eq(typ(input), function)
```

turns into this:
```typst
assert.eq(
      type(input),
      function,
)
```

This means my code often ends up being much longer vertically after formatting, making it much harder to navigate.

### Proposed Solution

It might be good to have some kind of check that detects how far horizontally the code reaches, and if the code is within the limit, format that code without line breaks.

I haven't looked at the codebase so I have no idea how easy this would be to implement, and I also don't know if this annoys enough people to be worth implementing, but I figured I'd bring it up.

**Comment by BattleCh1cken** [comment]
After switching to 0.11.22 I noticed a lot of these issues were fixed, particularly the first and second code snippets I used as examples.

**Comment by BattleCh1cken** [comment]
Do you mean the -c flag? To be honest, I'm somewhat blind, and didn't see that existed. I'll do some testing and come back with some more concrete examples if that doesn't fix my problem.

**Comment by Enter-tainer** [comment]
> After switching to 0.11.22 I noticed a lot of these issues were fixed

i'm not 100% sure but i think 0.11.17-0.11.20 doesnt touch related code..?

**Comment by BattleCh1cken** [comment]
Is there a way to specify the columns within the configuration for your editor?

**Comment by BattleCh1cken** [comment]
I think I'm just being silly, I'm gonna close this issue for now. If I have any more concrete problems that aren't just me not knowing how to use the tool, I'll let you know.
