### ISSUE TITLE
[Feeature request] Format list

### ISSUE THREAD

**Issue by Ciflire** [Enter-tainer/typstyle#83]
Why not format list just as if it was text/content etc with an indent in the beginning of each line of 2 (cf guidelines)
Before:
```typc
- $Lambda in CC$ est une valeur propre de $A$ s'il existe un vecteur $u in CC^n, u != 0$ tel que $A u = lambda u$. Le vecteur $u$ est appelé vecteur propre associé à $lambda$
- Les valeurs propres $lambda$ de $A$ sont les zeros du polynôme caractéristique $p_A(lambda) = det(A-lambda I)$. Le polynôme $p_A$ est de degré $n$ par rapport à $lambda$ donc il existe $n$ valeurs propres, non necessairement distinctes
- On note $S p(A)$ l'ensemble des valeurs propres de A (le spectre). On a $S p(A) = S p(A^top) "et" S p(A^*) = S p(macron(A))$
```

After: (I tried to respect the 80 chars but i don't know how that works exactly in the code
```
- $Lambda in CC$ est une valeur propre de $A$ s'il existe un vecteur $u in CC^n,
  u != 0$ tel que $A u = lambda u$. Le vecteur $u$ est appelé vecteur propre associé à
  $lambda$
- Les valeurs propres $lambda$ de $A$ sont les zeros du polynôme caractéristique
  $p_A(lambda) = det(A-lambda I)$. Le polynôme $p_A$ est de degré $n$ par rapport à $lambda$
  donc il existe $n$ valeurs propres, non necessairement distinctes
- On note $S p(A)$ l'ensemble des valeurs propres de A (le spectre). On a $S p(A)
  = S p(A^top) "et" S p(A^*) = S p(macron(A))$
```
Also i tried here, as you can see i added linebreaks inside of inline math and it did not break anything, spacing is automatic so any space seems to be "uninterpreted/rendered" in the document which means inline math can be formatted just as text is. Only problem is if there's a string inside, it must not be broken

(edit): PS sry this is a french document i'm writing, but i thin that's a good example

**Comment by Enter-tainer** [comment]
I see `nest(2)` in code but it seems that for some reason it doesn't work?
