### ISSUE TITLE
Add a blank line between heading and content?

### ISSUE THREAD

**Issue by ivaquero** [Enter-tainer/typstyle#84]
Could you please add a rule, “Add a blank line between heading and content?”.

**Comment by ivaquero** [comment]
And I think all the rules can be enumerated as what [ruff](https://docs.astral.sh/ruff/rules/) does.

**Comment by Enter-tainer** [comment]
I think they are different things. By adding an extra new line, it becomes a `parbreak()`

**Comment by Enter-tainer** [comment]
```
Markup: 10 [
    Heading: 5 [
        HeadingMarker: "=",
        Space: " ",
        Markup: 3 [
            Text: "123",
        ],
    ],
    Parbreak: "\n\n",
    Text: "456",
]
```

FYI

**Comment by Enter-tainer** [comment]
> And I think all the rules can be enumerated as what [ruff](https://docs.astral.sh/ruff/rules/) does.

The idea is good but I don't have enough time to implement all of them. Do you have a priority in your mind?

**Comment by ivaquero** [comment]
> > And I think all the rules can be enumerated as what [ruff](https://docs.astral.sh/ruff/rules/) does.
> 
> The idea is good but I don't have enough time to implement all of them. There is a whole company and engineering team behind ruff. And i work on typstyle part time as a hobby project. But, anyway, which rule do you think is important?

- I guess you can demonstrate some criteria, then we can join.
- To me, table-forming rules are more important.

**Comment by ivaquero** [comment]
For instance, the rules can be classified by objects, like Heading-relevant, Table-relevant, Math-relevant, etc.

**Comment by Enter-tainer** [comment]
thank you for your feedback! 

> I guess you can demonstrate some criteria, then we can join.

PR and idea are always welcome

**Comment by ivaquero** [comment]
Could you please show a list of rules? Then I will try to make a reasonable classification.

**Comment by ivaquero** [comment]
Sure.

**Comment by Enter-tainer** [comment]
Tracking in #85

**Comment by ivaquero** [comment]
Okay, and it would also be helpful for issue tracking.

**Comment by Enter-tainer** [comment]
The docs is avaliable at https://enter-tainer.github.io/typstyle/limitations/ @ivaquero
